// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCElK5tngVhFF7XWacAm5-cJR8hceH6eHQ',
    appId: '1:504698129582:web:44726d069f6a04bdb6f13f',
    messagingSenderId: '504698129582',
    projectId: 'cue-cast-app',
    authDomain: 'cue-cast-app.firebaseapp.com',
    storageBucket: 'cue-cast-app.firebasestorage.app',
    measurementId: 'G-9CT7CSF9NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8HkDXE7UWRu8DWTEeccGs0Cgz2UK0gy0',
    appId: '1:504698129582:android:efb6c82666a81685b6f13f',
    messagingSenderId: '504698129582',
    projectId: 'cue-cast-app',
    storageBucket: 'cue-cast-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yIMAWBoGiur6Ayd1N4hUoewn2TJMgUo',
    appId: '1:504698129582:ios:de36c6e2902848e9b6f13f',
    messagingSenderId: '504698129582',
    projectId: 'cue-cast-app',
    storageBucket: 'cue-cast-app.firebasestorage.app',
    iosBundleId: 'com.example.cueCastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_yIMAWBoGiur6Ayd1N4hUoewn2TJMgUo',
    appId: '1:504698129582:ios:de36c6e2902848e9b6f13f',
    messagingSenderId: '504698129582',
    projectId: 'cue-cast-app',
    storageBucket: 'cue-cast-app.firebasestorage.app',
    iosBundleId: 'com.example.cueCastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCElK5tngVhFF7XWacAm5-cJR8hceH6eHQ',
    appId: '1:504698129582:web:5b299ffa27ebfb5bb6f13f',
    messagingSenderId: '504698129582',
    projectId: 'cue-cast-app',
    authDomain: 'cue-cast-app.firebaseapp.com',
    storageBucket: 'cue-cast-app.firebasestorage.app',
    measurementId: 'G-DD36VMR9YH',
  );
}
